[project]
authors = ["Ansh <eye.am.ansh@gmail.com>"]
channels = ["conda-forge"]
name = "hbmenv"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
_libgcc_mutex = { version = "==0.1", build = "conda_forge" }
_openmp_mutex = { version = "==4.5", build = "2_gnu" }
bzip2 = { version = "==1.0.8", build = "h4bc722e_7" }
ca-certificates = { version = "==2025.4.26", build = "hbd8a1cb_0" }
ld_impl_linux-64 = { version = "==2.43", build = "h712a8e2_4" }
libexpat = { version = "==2.7.0", build = "h5888daf_0" }
libffi = { version = "==3.4.6", build = "h2dba641_1" }
libgcc = { version = "==14.2.0", build = "h767d61c_2" }
libgcc-ng = { version = "==14.2.0", build = "h69a702a_2" }
libgomp = { version = "==14.2.0", build = "h767d61c_2" }
liblzma = { version = "==5.8.1", build = "hb9d3cd8_0" }
liblzma-devel = { version = "==5.8.1", build = "hb9d3cd8_0" }
libnsl = { version = "==2.0.1", build = "hd590300_0" }
libsqlite = { version = "==3.49.1", build = "hee588c1_2" }
libstdcxx = { version = "==14.2.0", build = "h8f9b012_2" }
libstdcxx-ng = { version = "==14.2.0", build = "h4852527_2" }
libuuid = { version = "==2.38.1", build = "h0b41bf4_0" }
libxcrypt = { version = "==4.4.36", build = "hd590300_1" }
libzlib = { version = "==1.3.1", build = "hb9d3cd8_2" }
ncurses = { version = "==6.5", build = "h2d0b736_3" }
openssl = { version = "==3.5.0", build = "h7b32b05_1" }
pip = { version = "==25.1.1", build = "pyh8b19718_0" }
python = { version = "==3.10.17", build = "hd6af730_0_cpython" }
readline = { version = "==8.2", build = "h8c095d6_2" }
setuptools = { version = "==80.1.0", build = "pyhff2d567_0" }
sqlite = { version = "==3.49.1", build = "h9eae976_2" }
tk = { version = "==8.6.13", build = "noxft_h4845f30_101" }
valgrind = { version = "==3.25.0", build = "h629725b_0" }
wheel = { version = "==0.45.1", build = "pyhd8ed1ab_1" }
xz = { version = "==5.8.1", build = "hbcc6ac9_0" }
xz-gpl-tools = { version = "==5.8.1", build = "hbcc6ac9_0" }
xz-tools = { version = "==5.8.1", build = "hb9d3cd8_0" }
zlib = { version = "==1.3.1", build = "hb9d3cd8_2" }

[pypi-dependencies]
contourpy = "==1.3.1"
cycler = "==0.12.1"
cython = "==3.0.12"
fonttools = "==4.56.0"
kiwisolver = "==1.4.8"
matplotlib = "==3.10.1"
numpy = "==2.2.4"
packaging = "==24.2"
pandas = "==2.2.3"
pillow = "==11.1.0"
pyparsing = "==3.2.3"
python-dateutil = "==2.9.0.post0"
pytz = "==2025.2"
seaborn = "==0.13.2"
six = "==1.17.0"
tzdata = "==2025.2"
uv = "==0.6.10"

