name: Hardware-Level Verifications

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v27

      - name: Run sbt tests 
        run: nix develop --command sbt test

      - name: Clean 
        run: nix develop --command make clean