name: Simulation-Level Verifications

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v27

      - name: Run integration sanity tests to verify system is receiving and sending the correct data
        run: nix develop --command make verilog && make verilator-sanity-test

      - name: Clean 
        run: nix develop --command make clean